
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * alienHead
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function alienHead(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'alienHead', aFrame == undefined || aFrame == null? 'attack0000' : aFrame);
	this.scale.set(0.5, 0.5);
	this.animations.add('blink', ['blink0000', 'blink0001', 'blink0002', 'blink0003', 'blink0004', 'blink0005', 'blink0006', 'blink0007', 'blink0008', 'blink0009'], 15, false);
	this.animations.add('idle', ['idle0000'], 60, false);
	this.animations.add('attack', ['attack0000'], 1, false);
	
	this.myCreate();
	
}

/** @type Phaser.Sprite */
var alienHead_proto = Object.create(Phaser.Sprite.prototype);
alienHead.prototype = alienHead_proto;
alienHead.prototype.constructor = alienHead;

/* --- end generated code --- */
// -- user code here --

alienHead.prototype.myCreate = function(player,barra) {

	this.Blinktimer = this.game.time.create(false);
  	this.Blinktimer.loop(2000, this.blink, this);
    this.Blinktimer.start();


}

alienHead.prototype.blink = function() {
	this.animations.play('blink');
}

