
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * banner
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function banner(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'banner', aFrame == undefined || aFrame == null? 'Symbol 10 instance 10000' : aFrame);
	
}

/** @type Phaser.Sprite */
var banner_proto = Object.create(Phaser.Sprite.prototype);
banner.prototype = banner_proto;
banner.prototype.constructor = banner;

/* --- end generated code --- */
// -- user code here --
banner.prototype.update = function() {

	this.x-=0.5;
	
		if(this.x<=-1200){
			this.x = this.game.width+1200;
		}
	};