
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * enemyLifeBar.
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Phaser.Group} aParent The parent Group (or other {@link DisplayObject}) that this group will be added to.    If undefined/unspecified the Group will be added to the {@link Phaser.Game#world Game World}; if null the Group will not be added to any parent.
 * @param {string} aName A name for this group. Not used internally but useful for debugging.
 * @param {boolean} aAddToStage If true this group will be added directly to the Game.Stage instead of Game.World.
 * @param {boolean} aEnableBody If true all Sprites created with {@link #create} or {@link #createMulitple} will have a physics body created on them. Change the body type with {@link #physicsBodyType}.
 * @param {number} aPhysicsBodyType The physics body type to use when physics bodies are automatically added. See {@link #physicsBodyType} for values.
 */
function enemyLifeBar(aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType) {
	
	Phaser.Group.call(this, aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType);
	var _enemyLife = this.game.add.sprite(4.0, 5.0, 'enemyLife', null, this);
	_enemyLife.scale.set(0.5, 0.5);
	
	var _enemyLifeFull = this.game.add.sprite(5.0, 4.0, 'enemyLifeFull', null, this);
	_enemyLifeFull.scale.set(0.5, 0.5);
	
	var _enemyBar = this.game.add.sprite(0.0, 0.0, 'enemyBar', null, this);
	_enemyBar.scale.set(0.5, 0.5);
	
	
	
	// fields
	
	this.fEnemyLifeFull = _enemyLifeFull;
	
}

/** @type Phaser.Group */
var enemyLifeBar_proto = Object.create(Phaser.Group.prototype);
enemyLifeBar.prototype = enemyLifeBar_proto;
enemyLifeBar.prototype.constructor = enemyLifeBar;

/* --- end generated code --- */
// -- user code here --
