
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * expLabel
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function expLabel(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'buttons', aFrame == undefined || aFrame == null? 'expLabel0000' : aFrame);
	this.anchor.set(0.5, 0.5);
	var _anim_show = this.animations.add('show', ['expLabel0000', 'expLabel0001', 'expLabel0002', 'expLabel0003', 'expLabel0004'], 15, false);
	_anim_show.killOnComplete = true;
	_anim_show.play();
	
}

/** @type Phaser.Sprite */
var expLabel_proto = Object.create(Phaser.Sprite.prototype);
expLabel.prototype = expLabel_proto;
expLabel.prototype.constructor = expLabel;

/* --- end generated code --- */
// -- user code here --
