
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * explotion
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function explotion(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'alienHead', aFrame == undefined || aFrame == null? 'explotion0014' : aFrame);
	this.anchor.set(0.5, 0.5);
	var _anim_exploding = this.animations.add('exploding', ['explotion0000', 'explotion0001', 'explotion0002', 'explotion0003', 'explotion0004', 'explotion0005', 'explotion0006', 'explotion0007', 'explotion0008', 'explotion0009', 'explotion0010', 'explotion0011', 'explotion0012', 'explotion0013', 'explotion0014'], 45, false);
	_anim_exploding.killOnComplete = true;
	_anim_exploding.play();
	
}

/** @type Phaser.Sprite */
var explotion_proto = Object.create(Phaser.Sprite.prototype);
explotion.prototype = explotion_proto;
explotion.prototype.constructor = explotion;

/* --- end generated code --- */
// -- user code here --
