
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * kickPower
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function kickPower(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'wisherEnemy', aFrame == undefined || aFrame == null? 'kickPower0000' : aFrame);
	this.scale.set(2.0, 1.0);
	var _anim_powered = this.animations.add('powered', ['kickPower0000', 'kickPower0001', 'kickPower0002', 'kickPower0003', 'kickPower0004', 'kickPower0005', 'kickPower0006', 'kickPower0007'], 90, false);
	_anim_powered.killOnComplete = true;
	_anim_powered.play();
	
}

/** @type Phaser.Sprite */
var kickPower_proto = Object.create(Phaser.Sprite.prototype);
kickPower.prototype = kickPower_proto;
kickPower.prototype.constructor = kickPower;

/* --- end generated code --- */
// -- user code here --
