
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * LevelBarGlow
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function LevelBarGlow(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'buttons', aFrame == undefined || aFrame == null? 'levelBar0000' : aFrame);
	var _anim_glow = this.animations.add('glow', ['levelBar0000', 'levelBar0001', 'levelBar0002', 'levelBar0003', 'levelBar0004', 'levelBar0005', 'levelBar0006', 'levelBar0007', 'levelBar0008', 'levelBar0009', 'levelBar0010', 'levelBar0011', 'levelBar0012', 'levelBar0013', 'levelBar0014'], 15, true);
	_anim_glow.play();
	
}

/** @type Phaser.Sprite */
var LevelBarGlow_proto = Object.create(Phaser.Sprite.prototype);
LevelBarGlow.prototype = LevelBarGlow_proto;
LevelBarGlow.prototype.constructor = LevelBarGlow;

/* --- end generated code --- */
// -- user code here --
