
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * levelBar.
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Phaser.Group} aParent The parent Group (or other {@link DisplayObject}) that this group will be added to.
    If undefined/unspecified the Group will be added to the {@link Phaser.Game#world Game World}; if null the Group will not be added to any parent.
 * @param {string} aName A name for this group. Not used internally but useful for debugging.
 * @param {boolean} aAddToStage If true this group will be added directly to the Game.Stage instead of Game.World.
 * @param {boolean} aEnableBody If true all Sprites created with {@link #create} or {@link #createMulitple} will have a physics body created on them. Change the body type with {@link #physicsBodyType}.
 * @param {number} aPhysicsBodyType The physics body type to use when physics bodies are automatically added. See {@link #physicsBodyType} for values.
 */
function levelBar(aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType) {
	
	Phaser.Group.call(this, aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType);
	var _levelBarGlow = new LevelBarGlow(this.game, 55.0, 82.0);
	this.add(_levelBarGlow);
	
	this.game.add.sprite(0.0, 0.0, 'levelBg', null, this);
	
	var _levelText = this.game.add.text(44.0, 86.0, '00', {"font":"bold 40px Arial","fill":"#ffffff","align":"center"}, this);
	
	this.game.add.text(142.0, 95.0, 'exp. points', {"font":"bold 20px Arial","fill":"#ffffff","align":"center"}, this);
	
	var _moneyText = this.game.add.text(681.0, 85.0, '000001', {"font":"bold 40px Arial","fill":"#ffff80","stroke":"#ff8040","align":"right"}, this);
	
	
	
	// fields
	
	this.fLevelBarGlow = _levelBarGlow;
	this.fLevelText = _levelText;
	this.fMoneyText = _moneyText;
	
	this.myCreate();
	
}

/** @type Phaser.Group */
var levelBar_proto = Object.create(Phaser.Group.prototype);
levelBar.prototype = levelBar_proto;
levelBar.prototype.constructor = levelBar;

/* --- end generated code --- */
// -- user code here --
levelBar.prototype.myCreate = function() {
	this.fLevelText.boundsAlignH = 'center';
	this.fLevelText.setTextBounds(0, 0, 45, 0);
	this.totalLevelFill = 0

	this.timer = this.game.time.create(false);
    this.timer.loop(1000, this.customUpdate, this);
    this.timer.start();

}
levelBar.prototype.customUpdate = function() {
	
this.fLevelText.text = this.game.state.getCurrentState().fPlayer.myLevel;

this.fLevelBarGlow.scale.x = this.game.state.getCurrentState().fPlayer.currentFillLevel;


}
