
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * powerUp2
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function powerUp2(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'powerUps', aFrame == undefined || aFrame == null? 'core20000' : aFrame);
	this.scale.set(0.7, 0.7);
	this.anchor.set(0.5, 0.5);
	var _anim_powering = this.animations.add('powering', ['core20000', 'core20001', 'core20002', 'core20003', 'core20004', 'core20005', 'core20006', 'core20007', 'core20008', 'core20009', 'core20010', 'core20011', 'core20012', 'core20013', 'core20014', 'core20015', 'core20016', 'core20017', 'core20018', 'core20019'], 30, true);
	_anim_powering.play();
	this.game.physics.arcade.enable(this);
	this.body.setCircle(82.5, 1.4285736083984375, 77.14286804199219);
	this.body.velocity.x = -400.0;
	
	this.myCreate();
	
}

/** @type Phaser.Sprite */
var powerUp2_proto = Object.create(Phaser.Sprite.prototype);
powerUp2.prototype = powerUp2_proto;
powerUp2.prototype.constructor = powerUp2;

/* --- end generated code --- */
// -- user code here --
powerUp2.prototype.myCreate =  function(){
	
	this.myPower = 'speedForce';
	this.MyY = this.y + 30;
	this.tweenBtn = this.game.add.tween(this).to( {y:this.MyY}, 200, Phaser.Easing.Sinusoidal.InOut, true);
	this.tween2Btn = this.game.add.tween(this).to(  {y:this.y}, 200, Phaser.Easing.Sinusoidal.InOut, true);
	
	this.tweenBtn.chain(this.tween2Btn);
	this.tween2Btn.chain(this.tweenBtn);
	this.tweenBtn.start();
	
};

powerUp2.prototype.update = function() {
	if(this.x<=-100){
		this.destroy();
	}
};