
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * powerUp3
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function powerUp3(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'powerUps', aFrame == undefined || aFrame == null? 'core30000' : aFrame);
	this.scale.set(0.7, 0.7);
	this.anchor.set(0.5, 0.5);
	var _anim_powering = this.animations.add('powering', ['core30000', 'core30001', 'core30002', 'core30003', 'core30004', 'core30005', 'core30006', 'core30007', 'core30008', 'core30009', 'core30010', 'core30011', 'core30012', 'core30013', 'core30014', 'core30015', 'core30016', 'core30017', 'core30018', 'core30019'], 30, true);
	_anim_powering.play();
	this.game.physics.arcade.enable(this);
	this.body.setCircle(62.5, 24.28571319580078, 99.99999237060547);
	this.body.velocity.x = -400.0;
	
	this.myCreate();
	
}

/** @type Phaser.Sprite */
var powerUp3_proto = Object.create(Phaser.Sprite.prototype);
powerUp3.prototype = powerUp3_proto;
powerUp3.prototype.constructor = powerUp3;

/* --- end generated code --- */
// -- user code here --
powerUp3.prototype.myCreate =  function(){
	
	this.myPower = 'SuperShot';
	this.MyY = this.y + 30;
	this.tweenBtn = this.game.add.tween(this).to( {y:this.MyY}, 200, Phaser.Easing.Sinusoidal.InOut, true);
	this.tween2Btn = this.game.add.tween(this).to(  {y:this.y}, 200, Phaser.Easing.Sinusoidal.InOut, true);
	
	this.tweenBtn.chain(this.tween2Btn);
	this.tween2Btn.chain(this.tweenBtn);
	this.tweenBtn.start();
	
};
powerUp3.prototype.update = function() {

	if(this.x<=-100){
		
		this.destroy();
	}
};