
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * shipTurbo
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function shipTurbo(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'alienHead', aFrame == undefined || aFrame == null? 'Symbol 1 instance 10001' : aFrame);
	this.scale.set(0.5, 0.5);
	this.anchor.set(0.5, 0.5);
	var _anim_on = this.animations.add('on', ['Symbol 1 instance 10000', 'Symbol 1 instance 10001'], 10, true);
	_anim_on.play();
	
}

/** @type Phaser.Sprite */
var shipTurbo_proto = Object.create(Phaser.Sprite.prototype);
shipTurbo.prototype = shipTurbo_proto;
shipTurbo.prototype.constructor = shipTurbo;

/* --- end generated code --- */
// -- user code here --
